"""initial schema

Revision ID: f0406710e792
Revises:
Create Date: 2026-10-05 17:04:12.279592

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f0406710e792"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column("namespace", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("namespace", "key", name=op.f("pk_cache_entries")),
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column("labeler", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labels")),
    )
    op.create_index("ix_labels_target", "labels", ["target_type", "target_id"], unique=False)
    op.create_table(
        "research_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pack_id", sa.String(length=16), nullable=False),
        sa.Column("pack_version", sa.String(length=32), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("budget_usd", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("spent_usd", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("supports", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("derived_from", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("entailment_checked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_claims_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
    )
    op.create_index(op.f("ix_claims_run_id"), "claims", ["run_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("source_category", sa.String(length=32), nullable=True),
        sa.Column("quality_tier", sa.String(length=8), nullable=True),
        sa.Column("snippet_only", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text_hash", sa.String(length=64), nullable=True),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_documents_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("run_id", "canonical_url", name=op.f("uq_documents_run_id")),
    )
    op.create_index(op.f("ix_documents_domain"), "documents", ["domain"], unique=False)
    op.create_index(op.f("ix_documents_run_id"), "documents", ["run_id"], unique=False)
    op.create_table(
        "independence_groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("rule", sa.String(length=16), nullable=False),
        sa.Column("document_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_independence_groups_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_independence_groups")),
    )
    op.create_index(
        op.f("ix_independence_groups_run_id"), "independence_groups", ["run_id"], unique=False
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_id", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("response_id", sa.String(length=128), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_llm_calls_run_id_research_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index(op.f("ix_llm_calls_run_id"), "llm_calls", ["run_id"], unique=False)
    op.create_table(
        "problem_clusters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("signal_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("independent_source_count", sa.Integer(), nullable=False),
        sa.Column("source_category_mix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_strength", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_problem_clusters_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_problem_clusters")),
    )
    op.create_index(
        op.f("ix_problem_clusters_run_id"), "problem_clusters", ["run_id"], unique=False
    )
    op.create_table(
        "queries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("intent", sa.String(length=16), nullable=False),
        sa.Column("submarket", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_queries_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queries")),
        sa.UniqueConstraint("run_id", "text", name=op.f("uq_queries_run_id")),
    )
    op.create_index(op.f("ix_queries_run_id"), "queries", ["run_id"], unique=False)
    op.create_table(
        "stage_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_stage_runs_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_runs")),
    )
    op.create_index("ix_stage_runs_run_id_stage", "stage_runs", ["run_id", "stage"], unique=False)
    op.create_table(
        "competitors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("problem_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("segment", sa.Text(), nullable=True),
        sa.Column("geo", sa.String(length=64), nullable=True),
        sa.Column("pricing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem_clusters.id"],
            name=op.f("fk_competitors_problem_id_problem_clusters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_competitors_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitors")),
    )
    op.create_index(op.f("ix_competitors_problem_id"), "competitors", ["problem_id"], unique=False)
    op.create_index(op.f("ix_competitors_run_id"), "competitors", ["run_id"], unique=False)
    op.create_table(
        "excerpts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("verified", sa.String(length=8), nullable=False),
        sa.Column("author_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_excerpts_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_excerpts")),
    )
    op.create_index(op.f("ix_excerpts_document_id"), "excerpts", ["document_id"], unique=False)
    op.create_table(
        "gap_matrices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("problem_id", sa.BigInteger(), nullable=False),
        sa.Column("matrix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem_clusters.id"],
            name=op.f("fk_gap_matrices_problem_id_problem_clusters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gap_matrices")),
        sa.UniqueConstraint("problem_id", name=op.f("uq_gap_matrices_problem_id")),
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("problem_id", sa.BigInteger(), nullable=False),
        sa.Column("segment", sa.Text(), nullable=False),
        sa.Column("solution_angle", sa.Text(), nullable=False),
        sa.Column("buyer_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("economic_model", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("wtp_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem_clusters.id"],
            name=op.f("fk_opportunities_problem_id_problem_clusters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_opportunities_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    op.create_index(
        op.f("ix_opportunities_problem_id"), "opportunities", ["problem_id"], unique=False
    )
    op.create_index(op.f("ix_opportunities_run_id"), "opportunities", ["run_id"], unique=False)
    op.create_table(
        "search_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("query_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["queries.id"],
            name=op.f("fk_search_results_query_id_queries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_results")),
    )
    op.create_index(
        op.f("ix_search_results_query_id"), "search_results", ["query_id"], unique=False
    )
    op.create_table(
        "score_cards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attractiveness", sa.Float(), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("founder_fit", sa.String(length=8), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("rule_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_score_cards_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_cards")),
        sa.UniqueConstraint("opportunity_id", name=op.f("uq_score_cards_opportunity_id")),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("excerpt_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("actor", sa.Text(), nullable=True),
        sa.Column("workflow", sa.Text(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("first_hand", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["excerpt_id"],
            ["excerpts.id"],
            name=op.f("fk_signals_excerpt_id_excerpts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_signals_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index(op.f("ix_signals_excerpt_id"), "signals", ["excerpt_id"], unique=False)
    op.create_index(op.f("ix_signals_run_id"), "signals", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_run_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_excerpt_id"), table_name="signals")
    op.drop_table("signals")
    op.drop_table("score_cards")
    op.drop_index(op.f("ix_search_results_query_id"), table_name="search_results")
    op.drop_table("search_results")
    op.drop_index(op.f("ix_opportunities_run_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_problem_id"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_table("gap_matrices")
    op.drop_index(op.f("ix_excerpts_document_id"), table_name="excerpts")
    op.drop_table("excerpts")
    op.drop_index(op.f("ix_competitors_run_id"), table_name="competitors")
    op.drop_index(op.f("ix_competitors_problem_id"), table_name="competitors")
    op.drop_table("competitors")
    op.drop_index("ix_stage_runs_run_id_stage", table_name="stage_runs")
    op.drop_table("stage_runs")
    op.drop_index(op.f("ix_queries_run_id"), table_name="queries")
    op.drop_table("queries")
    op.drop_index(op.f("ix_problem_clusters_run_id"), table_name="problem_clusters")
    op.drop_table("problem_clusters")
    op.drop_index(op.f("ix_llm_calls_run_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_independence_groups_run_id"), table_name="independence_groups")
    op.drop_table("independence_groups")
    op.drop_index(op.f("ix_documents_run_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_domain"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_claims_run_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_table("research_runs")
    op.drop_index("ix_labels_target", table_name="labels")
    op.drop_table("labels")
    op.drop_table("cache_entries")
    # ### end Alembic commands ###
